/**
 * InpaintingTab Component
 *
 * Purpose:
 * - Allow users to remove objects or fill regions in images
 * - User uploads an image and draws/uploads a mask
 * - User provides a text prompt describing what to fill in the masked region
 * - Areas marked in the mask get regenerated by the diffusion model
 *
 * User Flow:
 * 1. Upload source image
 * 2. Draw mask over areas to edit (red overlay)
 * 3. Enter prompt describing desired content for masked area
 * 4. (Optional) Enter negative prompt for what to avoid
 * 5. (Optional) Select model and adjust settings
 * 6. Click Generate
 * 7. View/download result
 *
 * TODO:
 * - [x] Image upload component
 * - [x] Mask drawing canvas with brush/eraser
 * - [x] Prompt input (text describing what to fill)
 * - [x] Negative prompt input (what to avoid)
 * - [x] Model selection dropdown (SD Inpainting, SDXL Inpainting, etc.)
 * - [x] Generate button with validation
 * - [x] Result display area with side-by-side comparison
 * - [x] Download button for result
 * - [x] Loading state during API call
 * - [x] Error handling and user feedback
 * - [ ] Connect to backend API
 */

import { useState } from 'react'
import ImageUpload from './ImageUpload'
import MaskCanvas from './MaskCanvas'

// Available inpainting models
const INPAINTING_MODELS = [
  { id: 'sd-inpainting', name: 'Stable Diffusion Inpainting', vram: '5-7 GB' },
  { id: 'sdxl-inpainting', name: 'SDXL Inpainting', vram: '10-12 GB' },
  { id: 'kandinsky-inpainting', name: 'Kandinsky 2.2 Inpainting', vram: '6-8 GB' },
] as const

type ModelId = typeof INPAINTING_MODELS[number]['id']

function InpaintingTab() {
  // Image and mask state
  const [sourceImageUrl, setSourceImageUrl] = useState<string | null>(null)
  const [sourceImageFile, setSourceImageFile] = useState<File | null>(null)
  const [maskDataUrl, setMaskDataUrl] = useState<string | null>(null)

  // Generation parameters
  const [prompt, setPrompt] = useState('')
  const [negativePrompt, setNegativePrompt] = useState('')
  const [selectedModel, setSelectedModel] = useState<ModelId>('sd-inpainting')

  // Generation state
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [resultImageUrl, setResultImageUrl] = useState<string | null>(null)

  const handleSourceImageSelect = (file: File, previewUrl: string) => {
    setSourceImageUrl(previewUrl)
    setSourceImageFile(file)
    setMaskDataUrl(null)
    setResultImageUrl(null)
    setError(null)
  }

  const handleImageClear = () => {
    setSourceImageUrl(null)
    setSourceImageFile(null)
    setMaskDataUrl(null)
    setResultImageUrl(null)
    setError(null)
  }

  const handleMaskChange = (newMaskDataUrl: string | null) => {
    setMaskDataUrl(newMaskDataUrl)
  }

  const canGenerate = sourceImageUrl && maskDataUrl && prompt.trim().length > 0

  const handleGenerate = async () => {
    if (!canGenerate || !sourceImageFile) return

    setIsGenerating(true)
    setError(null)
    setResultImageUrl(null)

    try {
      // TODO: Implement actual API call to backend
      // For now, simulate a delay
      await new Promise(resolve => setTimeout(resolve, 2000))

      // Placeholder: In real implementation, this would be the result from the API
      // setResultImageUrl(response.imageUrl)

      // For demo purposes, show original image as "result"
      setResultImageUrl(sourceImageUrl)

      console.log('Generation params:', {
        model: selectedModel,
        prompt,
        negativePrompt,
        hasImage: !!sourceImageFile,
        hasMask: !!maskDataUrl,
      })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred during generation')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleDownload = () => {
    if (!resultImageUrl) return

    const link = document.createElement('a')
    link.href = resultImageUrl
    link.download = `inpainted-${Date.now()}.png`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div>
      <h2 className="text-xl font-semibold mb-4">Inpainting</h2>
      <p className="text-slate-400 mb-6">
        Remove objects or fill regions intelligently. Upload an image, paint over the area you want to edit, then describe what should fill that area.
      </p>

      {/* Step 1: Upload image */}
      {!sourceImageUrl && (
        <ImageUpload
          label="Source Image"
          onImageSelect={handleSourceImageSelect}
          onImageClear={handleImageClear}
        />
      )}

      {/* Step 2: Draw mask and configure generation */}
      {sourceImageUrl && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left column: Image and mask */}
          <div>
            {/* Change image button */}
            <div className="flex justify-between items-center mb-4">
              <span className="text-slate-300 font-medium">Draw mask on your image</span>
              <button
                onClick={handleImageClear}
                className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-300
                           rounded-lg text-sm transition-colors"
              >
                Change Image
              </button>
            </div>

            {/* Mask drawing canvas */}
            <MaskCanvas
              imageUrl={sourceImageUrl}
              onMaskChange={handleMaskChange}
            />
          </div>

          {/* Right column: Generation controls */}
          <div className="space-y-6">
            {/* Prompt input */}
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Prompt <span className="text-red-400">*</span>
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe what should fill the masked area... (e.g., 'a beautiful garden with flowers')"
                rows={3}
                className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg
                           text-slate-200 placeholder-slate-500 focus:outline-none
                           focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500
                           resize-none"
              />
            </div>

            {/* Negative prompt input */}
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Negative Prompt <span className="text-slate-500">(optional)</span>
              </label>
              <textarea
                value={negativePrompt}
                onChange={(e) => setNegativePrompt(e.target.value)}
                placeholder="What to avoid... (e.g., 'blurry, low quality, distorted')"
                rows={2}
                className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg
                           text-slate-200 placeholder-slate-500 focus:outline-none
                           focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500
                           resize-none"
              />
            </div>

            {/* Model selection */}
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Model
              </label>
              <select
                value={selectedModel}
                onChange={(e) => setSelectedModel(e.target.value as ModelId)}
                className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg
                           text-slate-200 focus:outline-none focus:border-indigo-500
                           focus:ring-1 focus:ring-indigo-500"
              >
                {INPAINTING_MODELS.map((model) => (
                  <option key={model.id} value={model.id}>
                    {model.name} ({model.vram})
                  </option>
                ))}
              </select>
            </div>

            {/* Generate button */}
            <button
              onClick={handleGenerate}
              disabled={!canGenerate || isGenerating}
              className={`w-full py-3 px-6 rounded-lg font-medium text-white
                          transition-all duration-200 flex items-center justify-center gap-2
                          ${canGenerate && !isGenerating
                            ? 'bg-indigo-600 hover:bg-indigo-700 cursor-pointer'
                            : 'bg-slate-700 cursor-not-allowed opacity-60'
                          }`}
            >
              {isGenerating ? (
                <>
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                      fill="none"
                    />
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    />
                  </svg>
                  Generating...
                </>
              ) : (
                'Generate'
              )}
            </button>

            {/* Validation hints */}
            {!maskDataUrl && sourceImageUrl && (
              <p className="text-amber-400 text-sm">
                Draw a mask on the image to mark the area you want to edit.
              </p>
            )}
            {maskDataUrl && !prompt.trim() && (
              <p className="text-amber-400 text-sm">
                Enter a prompt describing what should fill the masked area.
              </p>
            )}

            {/* Error display */}
            {error && (
              <div className="p-4 bg-red-900/30 border border-red-700 rounded-lg">
                <p className="text-red-400 text-sm">{error}</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Result display */}
      {resultImageUrl && (
        <div className="mt-8">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-medium text-slate-200">Result</h3>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white
                         rounded-lg text-sm font-medium transition-colors
                         flex items-center gap-2"
            >
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                      d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download
            </button>
          </div>

          {/* Side by side comparison */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p className="text-slate-400 text-sm mb-2">Original</p>
              <div className="rounded-lg overflow-hidden bg-slate-800">
                <img
                  src={sourceImageUrl!}
                  alt="Original"
                  className="w-full h-auto"
                />
              </div>
            </div>
            <div>
              <p className="text-slate-400 text-sm mb-2">Inpainted</p>
              <div className="rounded-lg overflow-hidden bg-slate-800">
                <img
                  src={resultImageUrl}
                  alt="Result"
                  className="w-full h-auto"
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default InpaintingTab
