/**
 * InpaintingTab Component
 *
 * Purpose:
 * - Allow users to remove objects or fill regions in images
 * - User uploads an image and draws/uploads a mask
 * - Areas marked in the mask get regenerated by the diffusion model
 *
 * TODO:
 * - [x] Add image upload component
 * - [x] Add mask drawing canvas
 * - [ ] Add prompt input for guiding inpainting
 * - [ ] Add negative prompt input (what to avoid)
 * - [ ] Add model selection dropdown
 * - [ ] Add generate button
 * - [ ] Add result display area
 * - [ ] Add download button for result
 * - [ ] Add loading state during generation
 * - [ ] Add error handling and display
 */

import { useState } from 'react'
import ImageUpload from './ImageUpload'
import MaskCanvas from './MaskCanvas'

function InpaintingTab() {
  const [sourceImageUrl, setSourceImageUrl] = useState<string | null>(null)
  const [maskDataUrl, setMaskDataUrl] = useState<string | null>(null)

  const handleSourceImageSelect = (_file: File, previewUrl: string) => {
    setSourceImageUrl(previewUrl)
    setMaskDataUrl(null) // Reset mask when new image is uploaded
  }

  const handleImageClear = () => {
    setSourceImageUrl(null)
    setMaskDataUrl(null)
  }

  const handleMaskChange = (newMaskDataUrl: string | null) => {
    setMaskDataUrl(newMaskDataUrl)
  }

  return (
    <div>
      <h2 className="text-xl font-semibold mb-4">Inpainting</h2>
      <p className="text-slate-400 mb-6">
        Remove objects or fill regions intelligently. Upload an image, then paint over the area you want to edit.
      </p>

      {/* Step 1: Upload image */}
      {!sourceImageUrl && (
        <ImageUpload
          label="Source Image"
          onImageSelect={handleSourceImageSelect}
          onImageClear={handleImageClear}
        />
      )}

      {/* Step 2: Draw mask on uploaded image */}
      {sourceImageUrl && (
        <div>
          {/* Change image button */}
          <div className="flex justify-between items-center mb-4">
            <span className="text-slate-300 font-medium">Draw mask on your image</span>
            <button
              onClick={handleImageClear}
              className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-300
                         rounded-lg text-sm transition-colors"
            >
              Change Image
            </button>
          </div>

          {/* Mask drawing canvas */}
          <MaskCanvas
            imageUrl={sourceImageUrl}
            onMaskChange={handleMaskChange}
          />

          {/* Placeholder for generation controls */}
          <div className="mt-6 p-4 bg-slate-800 rounded-lg">
            <p className="text-slate-300">
              {maskDataUrl
                ? 'Mask created. Prompt input and generate button coming next.'
                : 'Paint over the areas you want to edit, then proceed to generation.'}
            </p>
          </div>
        </div>
      )}
    </div>
  )
}

export default InpaintingTab
