/**
 * InpaintingTab Component
 *
 * Purpose:
 * - Allow users to remove objects or fill regions in images
 * - User uploads an image and draws/uploads a mask
 * - User provides a text prompt describing what to fill in the masked region
 * - Areas marked in the mask get regenerated by the diffusion model
 *
 * User Flow:
 * 1. Upload source image
 * 2. Draw mask over areas to edit (red overlay)
 * 3. Enter prompt describing desired content for masked area
 * 4. (Optional) Enter negative prompt for what to avoid
 * 5. (Optional) Select model and adjust settings
 * 6. Click Generate
 * 7. View/download result
 *
 * TODO:
 * - [x] Image upload component
 * - [x] Mask drawing canvas with brush/eraser
 * - [x] Prompt input (text describing what to fill)
 * - [x] Negative prompt input (what to avoid)
 * - [x] Model selection dropdown (SD Inpainting, SDXL Inpainting, etc.)
 * - [x] Generate button with validation
 * - [x] Result display area with side-by-side comparison
 * - [x] Download button for result
 * - [x] Loading state during API call
 * - [x] Error handling and user feedback
 * - [x] Connect to backend API
 */

import { useState } from 'react'
import ImageUpload from './ImageUpload'
import MaskCanvas from './MaskCanvas'
import { inpaintImage } from '../api'

// Available inpainting models
const INPAINTING_MODELS = [
  // Standard models
  { id: 'sd-inpainting', name: 'Stable Diffusion Inpainting', vram: '5-7 GB' },
  { id: 'kandinsky-inpainting', name: 'Kandinsky 2.2 Inpainting', vram: '6-8 GB' },
  // SDXL Inpainting variants
  { id: 'sdxl-inpainting', name: 'SDXL Inpainting', vram: '10-12 GB' },
  { id: 'sdxl-inpainting-8bit', name: 'SDXL Inpainting (8-bit)', vram: '~6 GB' },
  { id: 'sdxl-inpainting-4bit', name: 'SDXL Inpainting (4-bit)', vram: '~4 GB' },
  // FLUX.1 Fill variants
  { id: 'flux-fill', name: 'FLUX.1 Fill (Full)', vram: '22-24 GB' },
  { id: 'flux-fill-8bit', name: 'FLUX.1 Fill (8-bit)', vram: '~16 GB' },
  { id: 'flux-fill-4bit', name: 'FLUX.1 Fill (4-bit)', vram: '~10 GB' },
  { id: 'flux-fill-nf4', name: 'FLUX.1 Fill (NF4, Recommended)', vram: '~10 GB' },
] as const

type ModelId = typeof INPAINTING_MODELS[number]['id']

function InpaintingTab() {
  // Image and mask state
  const [sourceImageUrl, setSourceImageUrl] = useState<string | null>(null)
  const [sourceImageFile, setSourceImageFile] = useState<File | null>(null)
  const [maskDataUrl, setMaskDataUrl] = useState<string | null>(null)

  // Generation parameters
  const [prompt, setPrompt] = useState('')
  const [negativePrompt, setNegativePrompt] = useState('')
  const [selectedModel, setSelectedModel] = useState<ModelId>('sd-inpainting')

  // Advanced parameters
  const [guidanceScale, setGuidanceScale] = useState(7.5)
  const [numInferenceSteps, setNumInferenceSteps] = useState(30)
  const [strength, setStrength] = useState(1.0)
  const [seed, setSeed] = useState<number | null>(null)
  const [paddingMaskCrop, setPaddingMaskCrop] = useState<number | null>(null)
  const [showAdvanced, setShowAdvanced] = useState(false)

  // Generation state
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [resultImageUrl, setResultImageUrl] = useState<string | null>(null)

  const handleSourceImageSelect = (file: File, previewUrl: string) => {
    setSourceImageUrl(previewUrl)
    setSourceImageFile(file)
    setMaskDataUrl(null)
    setResultImageUrl(null)
    setError(null)
  }

  const handleImageClear = () => {
    setSourceImageUrl(null)
    setSourceImageFile(null)
    setMaskDataUrl(null)
    setResultImageUrl(null)
    setError(null)
  }

  const handleMaskChange = (newMaskDataUrl: string | null) => {
    setMaskDataUrl(newMaskDataUrl)
  }

  const canGenerate = sourceImageUrl && maskDataUrl && prompt.trim().length > 0

  const handleGenerate = async () => {
    if (!canGenerate || !sourceImageFile || !maskDataUrl) return

    setIsGenerating(true)
    setError(null)
    setResultImageUrl(null)

    try {
      const response = await inpaintImage({
        image: sourceImageFile,
        mask: maskDataUrl,
        prompt,
        negativePrompt: negativePrompt || undefined,
        model: selectedModel,
        guidanceScale,
        numInferenceSteps,
        strength,
        seed,
        paddingMaskCrop,
      })

      if (response.success && response.image) {
        setResultImageUrl(response.image)
        console.log('Inpainting completed:', {
          model: response.model_used,
          processingTime: response.processing_time,
        })
      } else {
        setError(response.error || 'Inpainting failed')
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred during generation')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleDownload = () => {
    if (!resultImageUrl) return

    // Detect format from data URL
    let extension = 'png'
    if (resultImageUrl.includes('image/jpeg') || resultImageUrl.includes('image/jpg')) {
      extension = 'jpg'
    } else if (resultImageUrl.includes('image/webp')) {
      extension = 'webp'
    }

    const link = document.createElement('a')
    link.href = resultImageUrl
    link.download = `inpainted-${Date.now()}.${extension}`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div>
      <h2 className="text-xl font-semibold mb-4">Inpainting</h2>
      <p className="text-slate-400 mb-6">
        Remove objects or fill regions intelligently. Upload an image, paint over the area you want to edit, then describe what should fill that area.
      </p>

      {/* Step 1: Upload image */}
      {!sourceImageUrl && (
        <ImageUpload
          label="Source Image"
          onImageSelect={handleSourceImageSelect}
          onImageClear={handleImageClear}
        />
      )}

      {/* Step 2: Draw mask and configure generation */}
      {sourceImageUrl && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left column: Image and mask */}
          <div>
            {/* Change image button */}
            <div className="flex justify-between items-center mb-4">
              <span className="text-slate-300 font-medium">Draw mask on your image</span>
              <button
                onClick={handleImageClear}
                className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-300
                           rounded-lg text-sm transition-colors"
              >
                Change Image
              </button>
            </div>

            {/* Mask drawing canvas */}
            <MaskCanvas
              imageUrl={sourceImageUrl}
              onMaskChange={handleMaskChange}
            />
          </div>

          {/* Right column: Generation controls */}
          <div className="space-y-6">
            {/* Prompt input */}
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Prompt <span className="text-red-400">*</span>
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe what should fill the masked area... (e.g., 'a beautiful garden with flowers')"
                rows={3}
                className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg
                           text-slate-200 placeholder-slate-500 focus:outline-none
                           focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500
                           resize-none"
              />
            </div>

            {/* Negative prompt input */}
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Negative Prompt <span className="text-slate-500">(optional)</span>
              </label>
              <textarea
                value={negativePrompt}
                onChange={(e) => setNegativePrompt(e.target.value)}
                placeholder="What to avoid... (e.g., 'blurry, low quality, distorted')"
                rows={2}
                className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg
                           text-slate-200 placeholder-slate-500 focus:outline-none
                           focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500
                           resize-none"
              />
            </div>

            {/* Model selection */}
            <div>
              <label className="block text-sm font-medium text-slate-300 mb-2">
                Model
              </label>
              <select
                value={selectedModel}
                onChange={(e) => setSelectedModel(e.target.value as ModelId)}
                className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg
                           text-slate-200 focus:outline-none focus:border-indigo-500
                           focus:ring-1 focus:ring-indigo-500"
              >
                {INPAINTING_MODELS.map((model) => (
                  <option key={model.id} value={model.id}>
                    {model.name} ({model.vram})
                  </option>
                ))}
              </select>
            </div>

            {/* Advanced Settings (collapsible) */}
            <div>
              <button
                type="button"
                onClick={() => setShowAdvanced(!showAdvanced)}
                className="flex items-center gap-2 text-sm font-medium text-slate-300 hover:text-slate-100 transition-colors"
              >
                <svg
                  className={`h-4 w-4 transition-transform ${showAdvanced ? 'rotate-90' : ''}`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
                Advanced Settings
              </button>

              {showAdvanced && (
                <div className="mt-3 space-y-4 p-4 bg-slate-800/50 border border-slate-700 rounded-lg">
                  {/* Guidance Scale */}
                  <div>
                    <div className="flex justify-between items-center mb-1">
                      <label className="text-sm font-medium text-slate-300">Guidance Scale</label>
                      <span className="text-sm text-slate-400">{guidanceScale}</span>
                    </div>
                    <input
                      type="range"
                      min={1.0}
                      max={20.0}
                      step={0.5}
                      value={guidanceScale}
                      onChange={(e) => setGuidanceScale(parseFloat(e.target.value))}
                      className="w-full accent-indigo-500"
                    />
                    <div className="flex justify-between text-xs text-slate-500 mt-0.5">
                      <span>1.0</span>
                      <span>20.0</span>
                    </div>
                  </div>

                  {/* Inference Steps */}
                  <div>
                    <div className="flex justify-between items-center mb-1">
                      <label className="text-sm font-medium text-slate-300">Inference Steps</label>
                      <span className="text-sm text-slate-400">{numInferenceSteps}</span>
                    </div>
                    <input
                      type="range"
                      min={10}
                      max={100}
                      step={1}
                      value={numInferenceSteps}
                      onChange={(e) => setNumInferenceSteps(parseInt(e.target.value))}
                      className="w-full accent-indigo-500"
                    />
                    <div className="flex justify-between text-xs text-slate-500 mt-0.5">
                      <span>10</span>
                      <span>100</span>
                    </div>
                  </div>

                  {/* Strength */}
                  <div>
                    <div className="flex justify-between items-center mb-1">
                      <label className="text-sm font-medium text-slate-300">Strength</label>
                      <span className="text-sm text-slate-400">{Math.round(strength * 100)}%</span>
                    </div>
                    <input
                      type="range"
                      min={0.0}
                      max={1.0}
                      step={0.05}
                      value={strength}
                      onChange={(e) => setStrength(parseFloat(e.target.value))}
                      className="w-full accent-indigo-500"
                    />
                    <div className="flex justify-between text-xs text-slate-500 mt-0.5">
                      <span>Preserve Original</span>
                      <span>Fully Regenerate</span>
                    </div>
                  </div>

                  {/* Seed */}
                  <div>
                    <label className="text-sm font-medium text-slate-300 mb-1 block">Seed</label>
                    <div className="flex gap-2">
                      <input
                        type="number"
                        min={0}
                        max={2147483647}
                        value={seed ?? ''}
                        onChange={(e) => setSeed(e.target.value === '' ? null : parseInt(e.target.value))}
                        placeholder="Random"
                        className="flex-1 px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg
                                   text-slate-200 placeholder-slate-500 focus:outline-none
                                   focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-sm"
                      />
                      <button
                        type="button"
                        onClick={() => setSeed(null)}
                        title="Randomize"
                        className="px-3 py-2 bg-slate-700 hover:bg-slate-600 text-slate-300
                                   rounded-lg text-sm transition-colors"
                      >
                        🎲
                      </button>
                    </div>
                    <p className="text-xs text-slate-500 mt-1">Leave empty for random seed</p>
                  </div>

                  {/* Padding Mask Crop */}
                  <div>
                    <label className="flex items-center gap-2 text-sm font-medium text-slate-300 mb-1">
                      <input
                        type="checkbox"
                        checked={paddingMaskCrop !== null}
                        onChange={(e) => setPaddingMaskCrop(e.target.checked ? 32 : null)}
                        className="rounded border-slate-600 bg-slate-800 accent-indigo-500"
                      />
                      Crop around mask region
                    </label>
                    {paddingMaskCrop !== null && (
                      <div className="mt-2">
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-xs text-slate-400">Padding</span>
                          <span className="text-sm text-slate-400">{paddingMaskCrop}px</span>
                        </div>
                        <input
                          type="range"
                          min={8}
                          max={256}
                          step={8}
                          value={paddingMaskCrop}
                          onChange={(e) => setPaddingMaskCrop(parseInt(e.target.value))}
                          className="w-full accent-indigo-500"
                        />
                        <div className="flex justify-between text-xs text-slate-500 mt-0.5">
                          <span>8px</span>
                          <span>256px</span>
                        </div>
                      </div>
                    )}
                    <p className="text-xs text-slate-500 mt-1">Focuses generation on the masked area (SD/SDXL only)</p>
                  </div>
                </div>
              )}
            </div>

            {/* Generate button */}
            <button
              onClick={handleGenerate}
              disabled={!canGenerate || isGenerating}
              className={`w-full py-3 px-6 rounded-lg font-medium text-white
                          transition-all duration-200 flex items-center justify-center gap-2
                          ${canGenerate && !isGenerating
                            ? 'bg-indigo-600 hover:bg-indigo-700 cursor-pointer'
                            : 'bg-slate-700 cursor-not-allowed opacity-60'
                          }`}
            >
              {isGenerating ? (
                <>
                  <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                      fill="none"
                    />
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    />
                  </svg>
                  Generating...
                </>
              ) : (
                'Generate'
              )}
            </button>

            {/* Validation hints */}
            {!maskDataUrl && sourceImageUrl && (
              <p className="text-amber-400 text-sm">
                Draw a mask on the image to mark the area you want to edit.
              </p>
            )}
            {maskDataUrl && !prompt.trim() && (
              <p className="text-amber-400 text-sm">
                Enter a prompt describing what should fill the masked area.
              </p>
            )}

            {/* Error display */}
            {error && (
              <div className="p-4 bg-red-900/30 border border-red-700 rounded-lg">
                <p className="text-red-400 text-sm">{error}</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Result display */}
      {resultImageUrl && (
        <div className="mt-8">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-medium text-slate-200">Result</h3>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white
                         rounded-lg text-sm font-medium transition-colors
                         flex items-center gap-2"
            >
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                      d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download
            </button>
          </div>

          {/* Side by side comparison */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p className="text-slate-400 text-sm mb-2">Original</p>
              <div className="rounded-lg overflow-hidden bg-slate-800">
                <img
                  src={sourceImageUrl!}
                  alt="Original"
                  className="w-full h-auto"
                />
              </div>
            </div>
            <div>
              <p className="text-slate-400 text-sm mb-2">Inpainted</p>
              <div className="rounded-lg overflow-hidden bg-slate-800">
                <img
                  src={resultImageUrl}
                  alt="Result"
                  className="w-full h-auto"
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default InpaintingTab
